import Cookies from "@/components/Cookies/Cookies";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Create Next App",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={(inter.className, "h-full")}>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {children}
        <Cookies></Cookies>
      </body>
    </html>
  );
}
