import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar/index"
import Cookies from "@/components/Cookies/Cookies";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={(inter.className, "h-full")}>
        <Navbar></Navbar>
        {children}
        <Cookies></Cookies>
      </body>
    </html>
  );
}
