import { auth } from "@/auth.js";
import { NavDashboard } from "@/components/NavDashboard/NavDashboard";
import { SideBar } from "@/components/SideBar/index";
import { DrawerProvider } from "@/components/SideBar/toggle";
import SelectRole from "./SelectRole/selectRole";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function ProfileLayout({ admin, user }) {
  const session = await auth();
  const role = session.user.role;

  return (
    <>
      {role === null ? (
        <div className="bg-slate-100 h-full">
          <DrawerProvider>
            <NavDashboard></NavDashboard>
            <SideBar role={role}></SideBar>
          </DrawerProvider>
          <div className="p-4 sm:ml-64">
            {/* <div className="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700 mt-14"> */}
            <div className="p-4 rounded-lg dark:border-gray-700 mt-14">
              {role === "admin" ? admin : user}
            </div>
          </div>
        </div>
      ) : (
        <SelectRole></SelectRole>
      )}
    </>
  );
}
